### PR TITLE
Feature/expose object to transform

### LINKED ISSUE #79: @Transform reference to "this"
Hello,

Sometimes, when de/serializing properties of an object, we need to apply specific rules. For example, let's say I have the following class:

```
class Test {
  a: string;
  b: boolean;
}
```

When using `classToPlain()`, I want `a` to be serialized only if `b` is `true`.

**Possible solutions**

- Give the `@Transform` callback the parent object as second argument: `@Transform((val, self) => self.b === true ? val : undefined)`
- Create a `@SerializeIf` and `@DeserializeIf` that can be used as follows: `@SerializeIf((val, self) => self.b === true)`

I like the first option as it does not add a new decorator.

All the best;

### PR DESCRIPTION
**Pull request by gempain**
Fixes #79 

Also fixes a compilation error that was introduced in another PR I guess.

### CODE REVIEW

**Comment by gempain** [comment]
Any new on this PR @pleerock ?

**Comment by gempain** [comment]
Thanks for merging :) @pleerock Looking forward to contributing more to this project :)

**Comment by pleerock** [comment]
Thank you for your contribution and sorry for a late response. Im quite busy with typeorm library right now and cannot afford myself to actively maintain other libraries as well (but I'll return activity back to them once majority of work on typeorm is done).

Your change was released in `0.1.8`

**Comment by gempain** [comment]
Do not worry, I just thought you'd end up passing at some point. Keep up the good work, and thanks for releasing the change today too :) Very appreciated :)

**Comment by gempain** [comment]
@pleerock Just noticed that some changes from my PR were not merged :/ I updated the docs to and exposed a third argument "transformationType" in the callback, but those changes seem to have gone away :/

**Pull request merged**
